# Generated by Django 5.0.4 on 2024-05-05 16:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_comment_text_modercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='modercomment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moder_comments', to='forum.post'),
            preserve_default=False,
        ),
    ]
