# Generated by Django 5.0.4 on 2024-05-05 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_modercomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modercomment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
