# Generated by Django 5.0.4 on 2024-05-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_modercomment_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modercomment',
            name='post',
        ),
        migrations.AlterField(
            model_name='modercomment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
