# Generated by Django 5.0.4 on 2024-05-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_remove_modercomment_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModerComment',
        ),
    ]
