# Generated by Django 5.0.4 on 2024-05-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_modercomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModerComment',
        ),
    ]
